-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "executiveId" DROP NOT NULL,
ALTER COLUMN "hodId" DROP NOT NULL,
ALTER COLUMN "managerId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Site" ALTER COLUMN "executiveId" DROP NOT NULL,
ALTER COLUMN "hodId" DROP NOT NULL,
ALTER COLUMN "managerId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "executiveId" DROP NOT NULL,
ALTER COLUMN "hodId" DROP NOT NULL,
ALTER COLUMN "managerId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "executiveId" DROP NOT NULL,
ALTER COLUMN "hodId" DROP NOT NULL,
ALTER COLUMN "managerId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Vendor" ALTER COLUMN "executiveId" DROP NOT NULL,
ALTER COLUMN "hodId" DROP NOT NULL,
ALTER COLUMN "managerId" DROP NOT NULL;
